/*In this game you need to crack the 4 digit code, each value of code may be occur once,more or not at all. Code is randomly
generated by the computer, each time the program runs a different code is generated */

#include <stdio.h>
#include <stdlib.h>
int main()
{
   int i,j,z,k,count,win,n,level,mode,player1,player2,turn;
   time_t t;

   printf("\n\n\n\t\t\tWelcome to 'CRACK THE CODE' \n\n" );
/*Ask the user if he wants to play against computer or human */
   printf("\n Enter 1 to play against computer\n\n Enter 2 for multi-player mode\n\n");
   scanf("%d",&mode);

/*If against computer set difficulty level*/
   if(mode==1)
   {
        printf("\n\n\n Select your difficulty level ! \n\n\n Enter 1 for Noob \n\n Enter 2 for Amateur \n\n Enter 3 for Professional \n\n");
        scanf("%d",&level);

        if(level==1)
        {
            n=4;
        }
        else if(level==2)
        {
            n=5;
        }
        else
        {
            n=6;
        }
    }
/*Set value n as 4 is human vs human*/
    if(mode==2)
    {
        n=4;
    }
int x[n],y[n];

/*If against computer generate a random code according to difficulty level */
    if(mode==1)
    {
/* Intializes random number generator */
        srand((unsigned) time(&t));

/* Generating an array of 4 random variables, the code is being generated ;)*/
        for(i=0;i<n;i++)
        {
            x[i]=rand()%n;
        }
/*Remove the comment below to check the code generated by the computer */
//        for(i=0;i<n;i++)
//        {
//            printf("\n%d",x[i]);
//        }
    }
/*Print instructions and welcome the user*/
   printf("\n\n\nIn this game you need to correctly enter a %d digit code in this manner: 1 2 3 4",n);
   printf("\nThe range of each value is from 0-%d, 0 and %d inclusive.",n,n);
   printf("\nEach value of code may be repeated or may not at all exist.");
   printf("\nIn total you have %d attempts,after each guess a hint maybe given ! \n\n\t\t\t\t GOOD LUCK !",n+1);

player1=0; //score player 1
player2=0; //score player 2

while(1)
{
/* Setting up players */
    if(mode==2)
    {
        printf("\n\n Player1 your score is %d \n Player2 your score is %d",player1,player2);
        printf("\n\n Which player would like to generate the code ? \n\n Enter 1 for Player 1 \n Enter 2 for Player 2 \n\n");
        scanf("%d",&turn);
        printf("\n\n Remember you need to enter 4 digits, each digit can be either 0,1,2,3,4 only !");
        printf("\n\n Player%d enter the code\n\n\t\t\t\t",turn);
/*Generate an array by the human ie the code*/
        for(i=0;i<n;i++)
        {
            scanf("%d",&x[i]);
        }
        if(turn==1)
        {
            printf("\n\n\n Player 2 you need to guess the code !");

        }
        if(turn==2)
        {
            printf("\n\n\n Player 1 you need to guess the code !");
        }
    }
/*Creating a loop for number of attempts */
for(i=0;i<n+1;i++)
   {
       win=0;

/*Asking the user for a guess and storing it in array y*/
        printf("\n\n\n Enter %d numbers with spaces: \n\n\t\t\t\t ",n);
        for(j=0;j<n;j++)
        {
            scanf("%d",&y[j]);
        }

/*Now we will compare each value of array x,the code generated by the computer,with array y,the code guessed by the user.*/
        for(z=0;z<n;z++)
        {

/*Tell the user which value has been entered correctly */
            if(x[z]==y[z])
            {
                printf("\n Value number %d of the code has been entered correctly \n",z+1);

/*Increment the counter if the value has been entered correctly */
                win++;
            }

/*Initialize count*/
            count=0;
            for(k=0;k<n;k++)
            {
/*If the guessed value of user is not present in the code, give a hint */
                if(y[z]!=x[k])
                {
                    count++;
                }
            }
            //printf("\n %d",count);
/*Count=4 when a given value is not part of code*/
            if(count==n)
            {
                printf("\n Value number %d is not a part of this code \n",z+1);
            }
/*If all the values have been entered correctly declare win */
            if(win==n)
            {
                printf("\n\n\t\t CONGRATULATIONS ! YOU HAVE WON THE GAME :D \n\n\n");
                i=n+1;
                if(mode==2)
                {
                    if(turn==1)
                    {
                        player2++;
                    }
                    if (turn==2)
                    {
                        player1++;
                    }
                }
            }
        }
   }
/*If the user has run out of attempts declare loss*/
    if(win!=n)
    {
        printf("\n\n\n\n\t\t\t SORRY :( YOU LOST ! BETTER LUCK NEXT TIME \n ");
        printf(" The correct answer is : \n\n\n\t\t\t");
        for(i=0;i<n;i++)
        {
            printf(" %d",x[i]);
        }
        printf("\n\n\n\n");
    }
    if(mode==1)
        break;
}
}
